version: 2.1

executors:
  android:
    docker:
    - image: circleci/android:api-29
    working_directory: ~/workspace
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'

commands:
  restore_gradle_cache:
    parameters: &gradle_cache_parameters
      cache_version:
        type: string
        default: v1
    steps:
      - restore_cache:
          keys:
            - gradle-<< parameters.cache_version >>-{{ checksum "./build.gradle" }}-{{ checksum "./library/build.gradle" }}
            - gradle-<< parameters.cache_version >>-{{ checksum "./build.gradle" }}-
            - gradle-<< parameters.cache_version >>-
            - gradle-
  save_gradle_cache:
    parameters: *gradle_cache_parameters
    steps:
      - save_cache:
          paths:
            - ~/.android
            - ~/.gradle
            - .gradle
            - ~/.m2
          key: gradle-<< parameters.cache_version >>-{{ checksum "./build.gradle" }}-{{ checksum "./library/build.gradle" }}

jobs:
  assemble_and_test:
    executor: android
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Run gradle tasks
          command: >
            ./gradlew
            :library:assembleRelease
            :library:test
      - save_gradle_cache

workflows:
  version: 2
  on_push:
    jobs:
      - assemble_and_test
